name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ellmo Run Evals
        uses: ellmo-ai/eval-gh-action@v0.0.1-prerelease   
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: example
          env_vars: |
            - OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true